require "./spec_helper"

# src/constants/lexers.cr is generated by scripts/lexer_metadata.py.
# This fails when the lexers directory changed (a lexer added, an alias
# renamed) and the script was not re-run, which is how the hcl and v
# aliases pointed at the wrong lexers for months.
describe "generated lexer constants" do
  it "match a fresh run of scripts/lexer_metadata.py" do
    root = File.expand_path("..", __DIR__)
    generated = File.tempname("lexers", ".cr")
    begin
      Process.run("python3", ["scripts/lexer_metadata.py", generated],
        chdir: root, output: Process::Redirect::Close,
        error: Process::Redirect::Inherit).success?.should be_true
      Process.run("crystal", ["tool", "format", generated],
        error: Process::Redirect::Inherit).success?.should be_true
      File.read(generated).should eq File.read(File.join(root, "src", "constants", "lexers.cr"))
    ensure
      File.delete?(generated)
    end
  end
end
