on: [push, pull_request]
name: Python Tests
jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19.x
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
        if [ -f python/requirements.dev.txt ]; then pip install -r python/requirements.dev.txt; fi
    - name: Build and install package
      run: |
        pip install setuptools wheel
        pip -v install --no-use-pep517 -e python
    - name: Test
      run: |
        pytest python/
